const Philanthropists = [
    {
      id: 1,
      name: 'John Doe',
      description: 'Founder of ABC Foundation',
      since: '12-12-2000',
      country: 'United States',
      donationAmount: 1000000,
    },
    {
      id: 2,
      name: 'Jane Smith',
      description: 'CEO of XYZ Charity',
      since: '08-06-1980',
      country: 'United Kingdom',
      donationAmount: 500000,
    },
    {
      id: 3,
      name: 'David Johnson',
      description: 'Philanthropist and Social Activist',
      since: '20-12-1998',
      country: 'Canada',
      donationAmount: 750000,
    },
    {
      id: 4,
      name: 'Sarah Thompson',
      description: 'Co-Founder of Education for All',
      since: '03-04-2005',
      country: 'Australia',
      donationAmount: 600000,
    },
    {
      id: 5,
      name: 'Robert Lee',
      description: 'Chairman of Health First Foundation',
      since: '11-09-1992',
      country: 'United States',
      donationAmount: 900000,
    },
    {
      id: 6,
      name: 'Emma Wilson',
      description: 'Founder of Green Earth Initiative',
      since: '27-07-2010',
      country: 'United Kingdom',
      donationAmount: 450000,
    },
    {
      id: 7,
      name: 'Michael Chen',
      description: 'Co-Founder of Hope for All',
      since: '18-02-2008',
      country: 'United States',
      donationAmount: 800000,
    },
    {
      id: 8,
      name: 'Sophia Liu',
      description: 'Director of Helping Hands Foundation',
      since: '09-11-1995',
      country: 'China',
      donationAmount: 550000,
    },
    {
      id: 9,
      name: 'Thomas Wilson',
      description: 'President of Goodwill Association',
      since: '06-03-2003',
      country: 'United States',
      donationAmount: 700000,
    },
    {
      id: 10,
      name: 'Olivia Brown',
      description: 'Founder of Bright Future Initiative',
      since: '22-09-2015',
      country: 'Canada',
      donationAmount: 400000,
    },
    {
      id: 11,
      name: 'William Davis',
      description: 'Chairman of Health and Hope Organization',
      since: '14-07-1999',
      country: 'United Kingdom',
      donationAmount: 950000,
    },
    {
      id: 12,
      name: 'Eva Martinez',
      description: 'Philanthropist and Humanitarian',
      since: '01-12-2002',
      country: 'Mexico',
      donationAmount: 300000,
    },
    {
      id: 13,
      name: 'Alexander Wilson',
      description: 'Co-Founder of Care Foundation',
      since: '28-05-1994',
      country: 'United States',
      donationAmount: 850000,
    },
    {
      id: 14,
      name: 'Sofia Rodriguez',
      description: 'CEO of Supportive Community',
      since: '17-10-2006',
      country: 'Spain',
      donationAmount: 500000,
    },
    {
      id: 15,
      name: 'James White',
      description: 'Founder of Equality for All',
      since: '02-03-2012',
      country: 'United States',
      donationAmount: 750000,
    },
    {
      id: 16,
      name: 'Emily Wilson',
      description: 'President of Better Tomorrow Foundation',
      since: '10-09-2004',
      country: 'United Kingdom',
      donationAmount: 550000,
    },
    {
      id: 17,
      name: 'Daniel Kim',
      description: 'Co-Founder of Hopeful Hearts',
      since: '25-06-1997',
      country: 'South Korea',
      donationAmount: 700000,
    },
    {
      id: 18,
      name: 'Sophie Martin',
      description: 'Chairwoman of Future Vision',
      since: '13-04-2001',
      country: 'France',
      donationAmount: 400000,
    },
    {
      id: 19,
      name: 'Matthew Harris',
      description: 'Founder of Brighter Days',
      since: '08-11-2016',
      country: 'United States',
      donationAmount: 900000,
    },
    {
      id: 20,
      name: 'Ava Johnson',
      description: 'CEO of Hope Foundation',
      since: '19-02-2009',
      country: 'Canada',
      donationAmount: 650000,
    },
    {
      id: 21,
      name: 'Ethan Thompson',
      description: 'Philanthropist and Environmentalist',
      since: '05-07-2007',
      country: 'United States',
      donationAmount: 800000,
    },
    {
      id: 22,
      name: 'Grace Clark',
      description: 'Co-Founder of Caring Souls',
      since: '12-01-1993',
      country: 'United Kingdom',
      donationAmount: 550000,
    },
  ];
  
  export default Philanthropists;
  